### ISSUE TITLE
Any real world React Native use case?

### ISSUE THREAD

**Issue by sunviwo** [zaguiini/formik-wizard#10]
Hi, I'd like to have a full example of use case in React Native. Thks

**Comment by zaguiini** [comment]
What do you mean? There are a lot of use cases. Think about this gargantuan form with 20+ fields you need to fill. I wouldn't like to see them all in a single page, so a kind of wizard or multi-step form would be needed to make it cleaner/clearer to the user as you could divide, split the form by sections. That alone is a valid case for this lib.

I'm closing this since it's not an issue with the library at all, but we can discuss it here.

**Comment by sunviwo** [comment]
Sorry if I didn't speak my mind the right way. It is obvious this kind of wizard is good for huge forms. I was asking if there could be a full example in React Native. The fact is that I was trying to use it in React Native and I got stuck at some point.

**Comment by zaguiini** [comment]
The usage is pretty much the same except for the component instantiation (e.g. `<FormikWizard />` part where you should handle it differently. It's stated on the README. Please create additional questions on StackOverflow since it would be the correct place to do so.

**Comment by ataravati** [comment]
@zaguiini No, the usage is not the same. There's not submit button in React Native, so that needs to be implemented differently as well.
