### ISSUE TITLE
Render props is deprecated

### ISSUE THREAD

**Issue by KROSF** [zaguiini/formik-wizard#11]
https://jaredpalmer.com/formik/docs/migrating-v2#deprecation-warnings

**Comment by zaguiini** [comment]
Mind filling a PR?

**Comment by michelts** [comment]
Should we stick to the Formik's approach and replace our `render` by a child callback function?

**Comment by zaguiini** [comment]
I guess so since we'll need the props

**Comment by michelts** [comment]
I mean, we certainly should replace our implementation and use the child callback function instead of the render prop, when using the `<Formik />` component, but I think we also should update the usage of the `<FormikWizard />` and expect a child callback function instead of a render method, so we speak the same language of formik itself.

**Comment by zaguiini** [comment]
We might support both! The `render` prop itself is not deprecated. Formik deprecated it in their library

**Comment by michelts** [comment]
You are right :) The render prop is still supported. I think we might support the child callback function and render prop, but trigger also a deprecation warning recommending to use a child callback also in `<FormikWizard />`.

**Comment by zaguiini** [comment]
Sounds good

**Comment by KROSF** [comment]
@zaguiini I will try to start the pr tomorrow

**Comment by joshudev** [comment]
Any progress on this?

**Comment by zaguiini** [comment]
I don't think so
