### ISSUE TITLE
Possible to pass props to Step components?

### ISSUE THREAD

**Issue by corysimmons** [zaguiini/formik-wizard#2]
If so, how?

**Comment by zaguiini** [comment]
No, not for now.

A possibility would be passing the `Step` component as a prop and letting the user mount it instead of rendering it as a `children` one.

What do you think about that? Could you submit a PR about that? A point would be not breaking compatibility because other projects depend on `formik-wizard` right now, so try to maintain it backwards compatible.

**Comment by corysimmons** [comment]
I ended up downgrading to react-albus alone and couldn't get it to play nice with NextJS so just had to roll my own solution in the end. Sorry but I don't have a use-case anymore.

**Comment by zaguiini** [comment]
You are more than welcome to submit a PR if you feel like it :)
